Repository wafflestudio/seminar-2022, pull requests merged in 2022-08, with the labels that each got.

#50 장승현 django 세미나 신청합니다
  seminar-list.md
Labels: Django

#52 박경록 Spring 신청합니다
  seminar-list.md
Labels: Spring, Django, android

#63 차동주 Spring 세미나 신청합니다
  seminar-list.md
Labels: Spring

#86 현준기 Django 세미나 신청합니다
  seminar-list.md
Labels: Django

#89 양찬혁 Spring 세미나 신청합니다
  seminar-list.md
Labels: Spring

#93 김좌훈 Spring 세미나 신청합니다
  seminar-list.md
Labels: Spring

#104 김수민 spring 세미나 신청합니다
  seminar-list.md
Labels: Spring

#122 박찬영 DjanGo 세미나 신청합니다
  seminar-list.md
Labels: Django

#126 김예지 react 세미나 신청합니다
  seminar-list.md
Labels: React

#127 이영은 react 세미나 신청합니다
  seminar-list.md
Labels: React

#143 류가은 android 세미나 신청합니다
  seminar-list.md
Labels: android

#148 송건우 android 세미나 신청합니다
  seminar-list.md
Labels: android

#174 최재훈 android 신청합니다.
  seminar-list.md
Labels: android

#184 박건률 iOS 세미나 신청합니다
  seminar-list.md
Labels: iOS
